### ISSUE TITLE
Crash after click render button

### ISSUE THREAD

**Issue by but0n** [pissang/paper-quilling-art#1]
![image](https://user-images.githubusercontent.com/7625588/67554036-20fe9180-f741-11e9-91c8-d029b291c783.png)

**Comment by pissang** [comment]
It may fail on some of the data. You can try using RANDOM or RESET button to regenerate the data.

![image](https://user-images.githubusercontent.com/841551/67554748-9028b580-f742-11e9-87f2-1879ff4dd41e.png)

![image](https://user-images.githubusercontent.com/841551/67554824-afbfde00-f742-11e9-827d-0d28e58175ac.png)

**Comment by but0n** [comment]
I've tried several times, and it still not working:

![image](https://user-images.githubusercontent.com/7625588/67555123-49878b00-f743-11e9-8e24-196f1e03cdc2.png)

The original renderer seems lost context, this issue probably associate with my graphics card. 🤔

**Comment by pissang** [comment]
Can you provide your log in console? Thanks

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/67573998-2fae6e00-f76c-11e9-9e6e-343cb2cd33d6.png)
![image](https://user-images.githubusercontent.com/7625588/67574017-35a44f00-f76c-11e9-8cc0-7e6f1a0d1026.png)

**Comment by pissang** [comment]
It seems to be caused by the denoiser I added recently. Perhaps because the size of texture I used is too large. I've removed the denoiser temporary, you can try it again:)

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/67749566-5d473000-fa68-11e9-9382-7839fe550792.png)
It works! Looks great!
